param(
    [Parameter(Mandatory = $true)]
    [string]$ShaderDirectory,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

$shaders = @(
    @{
        Name = 'UnlitVertexColorInstanced'
        File = 'UnlitVertexColorInstanced.hlsl'
        Delimiter = 'MRG_UVC'
    },
    @{
        Name = 'UnlitVertexColorTextureArrayInstanced'
        File = 'UnlitVertexColorTextureArrayInstanced.hlsl'
        Delimiter = 'MRG_UVCTA'
    },
    @{
        Name = 'Text'
        File = 'Text.hlsl'
        Delimiter = 'MRG_TEXT'
    }
)

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('// Generated by Shader/GenerateEmbeddedShaders.ps1.')
[void]$builder.AppendLine('// Edit the HLSL source files and rebuild; do not edit this file.')
[void]$builder.AppendLine()
[void]$builder.AppendLine('namespace mrg::graphics::detail::generated')
[void]$builder.AppendLine('{')

foreach ($shader in $shaders)
{
    $sourcePath = Join-Path $ShaderDirectory $shader.File
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf))
    {
        throw "Shader source was not found: $sourcePath"
    }

    $source = [System.IO.File]::ReadAllText($sourcePath)
    $delimiter = $shader.Delimiter
    if ($source.Contains(")$delimiter`""))
    {
        throw "The raw-string delimiter occurs in $sourcePath."
    }

    [void]$builder.AppendLine(
        "    inline constexpr char $($shader.Name)[] =")
    [void]$builder.Append("R`"$delimiter(")
    [void]$builder.Append($source)
    if (-not $source.EndsWith("`n"))
    {
        [void]$builder.AppendLine()
    }
    [void]$builder.AppendLine(")$delimiter`";")
    [void]$builder.AppendLine()
}

[void]$builder.AppendLine('}')

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container))
{
    [void](New-Item -ItemType Directory -Path $outputDirectory)
}

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText(
    [System.IO.Path]::GetFullPath($OutputPath),
    $builder.ToString(),
    $encoding)
