param(
    [Parameter(Mandatory = $true)]
    [string]$RepositoryRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

$publicHeaders = @(
    'Engine\Audio\System\AudioPlayback.h',
    'Engine\Audio\System\AudioSystem.h',
    'Engine\Audio\System\AudioPlaybackManager.h',
    'Engine\Platform.Win32\System\RuntimePaths.h',
    'Engine\Platform.Win32\Input\Input.h',
    'Engine\Collision\Query\Collision.h',
    'Engine\Geometry\Shape\Vertex.h',
    'Engine\Geometry\Shape\Shape.h',
    'Engine\Geometry\Primitive\RectangleShape.h',
    'Engine\Geometry\Primitive\CurvedRectangleShape.h',
    'Engine\Geometry\Primitive\CubeShape.h',
    'Engine\Geometry\Primitive\SphereShape.h',
    'Engine\Core\System\TransformNode.h',
    'Engine\Core\Visual2D\Visual2DNode.h',
    'Engine\Core\Visual2D\Visual2DCanvas.h',
    'Engine\Core\Visual2D\Visual2DComponents.h',
    'Engine\Core\Visual2D\Visual2DInputRouter.h',
    'Engine\Core\Visual2D\Visual2DSurface.h',
    'Engine\Core\Visual2D\Visual2DWidgets.h',
    'Engine\Graphics.D3D12\Text\TextRendering.h',
    'Engine\Graphics.D3D12\Texture\TextureManager.h',
    'Engine\Graphics.D3D12\Mesh\MeshRendering.h',
    'Engine\Graphics.D3D12\Renderer\D3D12Renderer.h',
    'Engine\Graphics.D3D12\Visual2D\Visual2DRendering.h',
    'Engine\Core\Client\IGameClient.h',
    'Engine\Core\System\HighResolutionClock.h',
    'Engine\Core\System\Camera.h',
    'Engine\Core\App\Engine.h',
    'Engine\Core\Scene\GameScene.h',
    'Engine\Core\System\MeshInstance.h',
    'Engine\Core\Scene\SceneManager.h',
    'Engine\Core\Client\SceneGameClient.h'
)

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('#pragma once')
[void]$builder.AppendLine()
[void]$builder.AppendLine('// Generated by Engine/SDK/GenerateCoreHeader.ps1.')
[void]$builder.AppendLine('// Do not edit this file directly; edit the feature headers instead.')
[void]$builder.AppendLine()
[void]$builder.AppendLine('#if defined(_MSC_VER) && !defined(MRG_CORE_NO_AUTOLINK)')
[void]$builder.AppendLine('#pragma comment(lib, "MRG.Core.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "d3d12.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "d3dcompiler.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "dxgi.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "dxguid.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "windowscodecs.lib")')
[void]$builder.AppendLine('#pragma comment(lib, "dwrite.lib")')
[void]$builder.AppendLine('#if defined(_DEBUG)')
[void]$builder.AppendLine('#pragma comment(lib, "fmodL_vc.lib")')
[void]$builder.AppendLine('#else')
[void]$builder.AppendLine('#pragma comment(lib, "fmod_vc.lib")')
[void]$builder.AppendLine('#endif')
[void]$builder.AppendLine('#endif')
[void]$builder.AppendLine()

foreach ($relativePath in $publicHeaders)
{
    $sourcePath = Join-Path $RepositoryRoot $relativePath
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf))
    {
        throw "Public header was not found: $sourcePath"
    }

    [void]$builder.AppendLine("// ===== BEGIN $relativePath =====")
    foreach ($line in [System.IO.File]::ReadAllLines($sourcePath))
    {
        if ($line -match '^\s*#pragma\s+once\s*$')
        {
            continue
        }
        if ($line -match '^\s*#include\s+"[^"]+"\s*$')
        {
            continue
        }
        [void]$builder.AppendLine($line)
    }
    [void]$builder.AppendLine("// ===== END $relativePath =====")
    [void]$builder.AppendLine()
}

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container))
{
    [void](New-Item -ItemType Directory -Path $outputDirectory)
}

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText(
    [System.IO.Path]::GetFullPath($OutputPath),
    $builder.ToString(),
    $encoding)
