#pragma once

// Generated by Engine/SDK/GenerateCoreHeader.ps1.
// Do not edit this file directly; edit the feature headers instead.

#if defined(_MSC_VER) && !defined(MRG_CORE_NO_AUTOLINK)
#pragma comment(lib, "MRG.Core.lib")
#pragma comment(lib, "d3d12.lib")
#pragma comment(lib, "d3dcompiler.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "dxguid.lib")
#pragma comment(lib, "windowscodecs.lib")
#pragma comment(lib, "dwrite.lib")
#if defined(_DEBUG)
#pragma comment(lib, "fmodL_vc.lib")
#else
#pragma comment(lib, "fmod_vc.lib")
#endif
#endif

// ===== BEGIN Engine\Audio\System\AudioSystem.h =====

// Audio feature: backend-neutral public service and backend contract.

#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

namespace mrg::audio
{
    enum class AudioOutputBackend
    {
        Automatic,
        Wasapi,
        Asio,
        NoSound,
    };

    struct AudioDeviceInfo
    {
        AudioOutputBackend backend{AudioOutputBackend::Automatic};
        int driverIndex{-1};
        std::string name;
        int sampleRate{};
        int speakerChannels{};
    };

    struct AudioConfig
    {
        AudioOutputBackend preferredBackend{AudioOutputBackend::Automatic};
        int driverIndex{-1};
        int maxVirtualChannels{256};
        std::uint32_t dspBufferLength{256};
        int dspBufferCount{4};
        bool fallBackToWasapi{true};
        bool allowNoSoundFallback{true};
        void* nativeWindowHandle{};
    };

    class IAudioBackend
    {
    public:
        virtual ~IAudioBackend() = default;

        [[nodiscard]] virtual bool Initialize(
            const AudioConfig& config,
            std::string& errorMessage) = 0;
        virtual void Update() = 0;
        virtual void Shutdown() noexcept = 0;

        [[nodiscard]] virtual std::string_view Name() const noexcept = 0;
        [[nodiscard]] virtual AudioOutputBackend ActiveOutput() const noexcept = 0;
        [[nodiscard]] virtual int SampleRate() const noexcept = 0;
        [[nodiscard]] virtual std::uint64_t DspClock() const noexcept = 0;
        [[nodiscard]] virtual const std::vector<AudioDeviceInfo>&
            OutputDevices() const noexcept = 0;
    };

    using AudioBackendFactory = std::unique_ptr<IAudioBackend> (*)();

    [[nodiscard]] std::unique_ptr<IAudioBackend> CreateFmodAudioBackend();

    // Public backend-neutral audio service exposed to the rest of the engine.
    // Run creates it before Client initialization and calls Update at the
    // independently configured audio cadence.  Client code only sees this
    // contract, so the FMOD backend can later be replaced without API changes.
    class AudioSystem final
    {
    public:
        AudioSystem() = default;
        ~AudioSystem();

        AudioSystem(const AudioSystem&) = delete;
        AudioSystem& operator=(const AudioSystem&) = delete;

        [[nodiscard]] bool Initialize(
            const AudioConfig& config,
            AudioBackendFactory factory,
            std::string& errorMessage);
        void Update();
        void Shutdown() noexcept;

        [[nodiscard]] bool IsInitialized() const noexcept;
        [[nodiscard]] std::string_view BackendName() const noexcept;
        [[nodiscard]] AudioOutputBackend ActiveOutput() const noexcept;
        [[nodiscard]] int SampleRate() const noexcept;
        [[nodiscard]] std::uint64_t DspClock() const noexcept;
        [[nodiscard]] const std::vector<AudioDeviceInfo>&
            OutputDevices() const noexcept;

    private:
        std::unique_ptr<IAudioBackend> backend_;
        bool initialized_{};
    };
}
// ===== END Engine\Audio\System\AudioSystem.h =====

// ===== BEGIN Engine\Platform.Win32\System\RuntimePaths.h =====

// Process-relative path helpers owned by the Win32 platform layer. Client
// code can locate packaged assets without depending on its working directory
// or calling Win32 APIs directly.

#include <filesystem>

namespace mrg::platform
{
    [[nodiscard]] std::filesystem::path ExecutablePath();
    [[nodiscard]] std::filesystem::path ExecutableDirectory();

    // Absolute paths pass through unchanged. Relative paths are resolved from
    // the directory containing the current process executable.
    [[nodiscard]] std::filesystem::path ResolveExecutableRelativePath(
        const std::filesystem::path& path);
}
// ===== END Engine\Platform.Win32\System\RuntimePaths.h =====

// ===== BEGIN Engine\Platform.Win32\Input\Input.h =====

// Input feature: timestamped Win32 Raw Input state and events.

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

namespace mrg::platform
{
    enum class MouseButton : std::uint8_t
    {
        Left,
        Right,
        Middle,
        X1,
        X2,
        Count,
    };

    enum class InputEventType : std::uint8_t
    {
        KeyPressed,
        KeyReleased,
        MouseButtonPressed,
        MouseButtonReleased,
        MouseMoved,
        MouseWheel,
    };

    struct InputEvent
    {
        InputEventType type{};
        std::uint16_t code{};
        std::int32_t valueX{};
        std::int32_t valueY{};
        float wheelDelta{};
        std::int64_t performanceCounterTicks{};
    };

    // Public snapshot and timestamped event stream populated by Win32 Raw Input.
    // PumpMessages begins a fresh update turn before dispatching messages:
    // pressed/released, mouse deltas, wheel, and Events() are therefore only
    // for that turn, while IsKeyDown/IsMouseButtonDown persist as held state.
    class InputState final
    {
    public:
        // Accepts a Win32 Virtual-Key value (for example VK_ESCAPE or 'W').
        // Raw Input keeps left/right modifier keys distinct, so query
        // VK_LSHIFT/VK_RSHIFT, VK_LCONTROL/VK_RCONTROL, or VK_LMENU/VK_RMENU.
        [[nodiscard]] bool IsKeyDown(std::uint16_t virtualKey) const noexcept;
        [[nodiscard]] bool WasKeyPressed(
            std::uint16_t virtualKey) const noexcept;
        [[nodiscard]] bool WasKeyReleased(
            std::uint16_t virtualKey) const noexcept;

        [[nodiscard]] bool IsMouseButtonDown(MouseButton button) const noexcept;
        [[nodiscard]] bool WasMouseButtonPressed(MouseButton button) const noexcept;
        [[nodiscard]] bool WasMouseButtonReleased(MouseButton button) const noexcept;

        [[nodiscard]] std::int32_t MouseDeltaX() const noexcept;
        [[nodiscard]] std::int32_t MouseDeltaY() const noexcept;
        // Absolute Win32 client coordinates are a pointer-placement snapshot.
        // Raw Input events remain the authoritative timestamped input stream.
        [[nodiscard]] std::int32_t MousePositionX() const noexcept;
        [[nodiscard]] std::int32_t MousePositionY() const noexcept;
        [[nodiscard]] bool IsMouseInsideWindow() const noexcept;
        [[nodiscard]] float MouseWheelDelta() const noexcept;
        [[nodiscard]] std::span<const InputEvent> Events() const noexcept;
        [[nodiscard]] std::int64_t PerformanceCounterFrequency() const noexcept;

    private:
        friend class Win32Window;

        static constexpr std::size_t KeyCount = 256;
        static constexpr std::size_t MouseButtonCount =
            static_cast<std::size_t>(MouseButton::Count);
        static constexpr std::size_t MaximumEventsPerUpdate = 256;

        void BeginUpdate() noexcept;
        void Reset() noexcept;
        void SetPerformanceCounterFrequency(std::int64_t frequency) noexcept;
        void SetKey(
            std::uint16_t virtualKey,
            bool isDown,
            std::int64_t timestamp) noexcept;
        void SetMouseButton(
            MouseButton button,
            bool isDown,
            std::int64_t timestamp) noexcept;
        void AddMouseDelta(
            std::int32_t x,
            std::int32_t y,
            std::int64_t timestamp) noexcept;
        void SetMousePosition(
            std::int32_t x,
            std::int32_t y,
            bool insideWindow) noexcept;
        void AddMouseWheel(float delta, std::int64_t timestamp) noexcept;
        void PushEvent(const InputEvent& event) noexcept;

        std::array<bool, KeyCount> keysDown_{};
        std::array<bool, KeyCount> keysPressed_{};
        std::array<bool, KeyCount> keysReleased_{};
        std::array<bool, MouseButtonCount> mouseButtonsDown_{};
        std::array<bool, MouseButtonCount> mouseButtonsPressed_{};
        std::array<bool, MouseButtonCount> mouseButtonsReleased_{};
        std::int32_t mouseDeltaX_{};
        std::int32_t mouseDeltaY_{};
        std::int32_t mousePositionX_{};
        std::int32_t mousePositionY_{};
        bool mouseInsideWindow_{};
        float mouseWheelDelta_{};
        std::array<InputEvent, MaximumEventsPerUpdate> events_{};
        std::size_t eventCount_{};
        std::int64_t performanceCounterFrequency_{};
    };
}
// ===== END Engine\Platform.Win32\Input\Input.h =====

// ===== BEGIN Engine\Collision\Query\Collision.h =====

// Backend-neutral 2D/3D collision primitives and stateless intersection
// queries. All positions and sizes use engine world units.

#include <DirectXMath.h>

#include <optional>

namespace mrg::collision
{
    inline constexpr float DefaultEpsilon = 1.0e-5F;

    struct Line2D
    {
        DirectX::XMFLOAT2 point{};
        DirectX::XMFLOAT2 direction{1.0F, 0.0F};
    };

    struct LineSegment2D
    {
        DirectX::XMFLOAT2 start{};
        DirectX::XMFLOAT2 end{};
    };

    struct Circle2D
    {
        DirectX::XMFLOAT2 center{};
        float radius{};
    };

    // rotationRadians rotates the local X axis counter-clockwise.
    struct Obb2D
    {
        DirectX::XMFLOAT2 center{};
        DirectX::XMFLOAT2 halfExtents{0.5F, 0.5F};
        float rotationRadians{};
    };

    struct Line3D
    {
        DirectX::XMFLOAT3 point{};
        DirectX::XMFLOAT3 direction{1.0F, 0.0F, 0.0F};
    };

    struct Ray3D
    {
        DirectX::XMFLOAT3 origin{};
        DirectX::XMFLOAT3 direction{1.0F, 0.0F, 0.0F};
    };

    struct LineSegment3D
    {
        DirectX::XMFLOAT3 start{};
        DirectX::XMFLOAT3 end{};
    };

    // Plane equation: dot(normal, point) = distanceFromOrigin.
    // The normal does not have to be normalized.
    struct Plane3D
    {
        DirectX::XMFLOAT3 normal{0.0F, 1.0F, 0.0F};
        float distanceFromOrigin{};
    };

    struct Sphere3D
    {
        DirectX::XMFLOAT3 center{};
        float radius{};
    };

    struct Triangle3D
    {
        DirectX::XMFLOAT3 first{};
        DirectX::XMFLOAT3 second{};
        DirectX::XMFLOAT3 third{};
    };

    // orientation is a quaternion in (x, y, z, w) order. It is normalized
    // internally before a query.
    struct Obb3D
    {
        DirectX::XMFLOAT3 center{};
        DirectX::XMFLOAT3 halfExtents{0.5F, 0.5F, 0.5F};
        DirectX::XMFLOAT4 orientation{0.0F, 0.0F, 0.0F, 1.0F};
    };

    struct LineHit3D
    {
        DirectX::XMFLOAT3 point{};
        DirectX::XMFLOAT3 normal{};

        // point + direction * parameter for Line3D, origin + direction *
        // parameter for Ray3D, and lerp(start, end, parameter) for a segment.
        // Segment parameters are clamped to [0, 1].
        float parameter{};
    };

    struct TriangleHit3D
    {
        DirectX::XMFLOAT3 point{};
        DirectX::XMFLOAT3 normal{};
        // Weights for first, second, and third. They sum to one and can be
        // used to interpolate UVs or other per-vertex attributes.
        DirectX::XMFLOAT3 barycentric{};
        float parameter{};
    };

    [[nodiscard]] DirectX::XMFLOAT2 ClosestPoint(
        const LineSegment2D& segment,
        const DirectX::XMFLOAT2& point) noexcept;
    [[nodiscard]] DirectX::XMFLOAT2 ClosestPoint(
        const Obb2D& box,
        const DirectX::XMFLOAT2& point) noexcept;

    [[nodiscard]] bool Intersects(
        const Circle2D& circle,
        const Line2D& line,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Circle2D& circle,
        const LineSegment2D& segment,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Circle2D& circle,
        const Obb2D& box,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Obb2D& first,
        const Obb2D& second,
        float epsilon = DefaultEpsilon) noexcept;

    [[nodiscard]] bool Intersects(
        const Line2D& line,
        const Circle2D& circle,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const LineSegment2D& segment,
        const Circle2D& circle,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Obb2D& box,
        const Circle2D& circle,
        float epsilon = DefaultEpsilon) noexcept;

    // A coplanar line/ray/segment returns a representative hit at parameter
    // zero. Parallel objects on separate planes return std::nullopt.
    [[nodiscard]] std::optional<LineHit3D> Intersect(
        const Plane3D& plane,
        const Line3D& line,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] std::optional<LineHit3D> Intersect(
        const Plane3D& plane,
        const Ray3D& ray,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] std::optional<LineHit3D> Intersect(
        const Plane3D& plane,
        const LineSegment3D& segment,
        float epsilon = DefaultEpsilon) noexcept;

    [[nodiscard]] bool Intersects(
        const Plane3D& plane,
        const Line3D& line,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Plane3D& plane,
        const Ray3D& ray,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Plane3D& plane,
        const LineSegment3D& segment,
        float epsilon = DefaultEpsilon) noexcept;

    // Moller-Trumbore ray/triangle query. Winding is preserved in the
    // returned normal; callers decide whether to reject a back face.
    [[nodiscard]] std::optional<TriangleHit3D> Intersect(
        const Triangle3D& triangle,
        const Ray3D& ray,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Triangle3D& triangle,
        const Ray3D& ray,
        float epsilon = DefaultEpsilon) noexcept;

    [[nodiscard]] bool Intersects(
        const Sphere3D& sphere,
        const Line3D& line,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Sphere3D& sphere,
        const Ray3D& ray,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Sphere3D& sphere,
        const LineSegment3D& segment,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Sphere3D& sphere,
        const Obb3D& box,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Obb3D& first,
        const Obb3D& second,
        float epsilon = DefaultEpsilon) noexcept;

    [[nodiscard]] bool Intersects(
        const Line3D& line,
        const Sphere3D& sphere,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Ray3D& ray,
        const Sphere3D& sphere,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const LineSegment3D& segment,
        const Sphere3D& sphere,
        float epsilon = DefaultEpsilon) noexcept;
    [[nodiscard]] bool Intersects(
        const Obb3D& box,
        const Sphere3D& sphere,
        float epsilon = DefaultEpsilon) noexcept;
}
// ===== END Engine\Collision\Query\Collision.h =====

// ===== BEGIN Engine\Geometry\Shape\Vertex.h =====

// Shape feature: backend-neutral canonical and selectable vertex layouts.

#include <DirectXMath.h>

#include <concepts>
#include <type_traits>

namespace mrg::geometry
{
    // Public canonical attributes retained by Shape regardless of the GPU vertex
    // layout selected by a Client.
    struct VertexAttributes final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT2 uv{};
        DirectX::XMFLOAT3 normal{};
        DirectX::XMFLOAT4 color{1.0F, 1.0F, 1.0F, 1.0F};
    };

    struct VertexPosition final
    {
        DirectX::XMFLOAT3 position{};

        [[nodiscard]] static VertexPosition FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {attributes.position};
        }
    };

    struct VertexPositionUv final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT2 uv{};

        [[nodiscard]] static VertexPositionUv FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {attributes.position, attributes.uv};
        }
    };

    struct VertexPositionColor final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT4 color{};

        [[nodiscard]] static VertexPositionColor FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {attributes.position, attributes.color};
        }
    };

    struct VertexPositionUvColor final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT2 uv{};
        DirectX::XMFLOAT4 color{};

        [[nodiscard]] static VertexPositionUvColor FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {
                attributes.position,
                attributes.uv,
                attributes.color};
        }
    };

    struct VertexPositionNormal final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT3 normal{};

        [[nodiscard]] static VertexPositionNormal FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {attributes.position, attributes.normal};
        }
    };

    struct VertexPositionNormalUv final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT3 normal{};
        DirectX::XMFLOAT2 uv{};

        [[nodiscard]] static VertexPositionNormalUv FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {
                attributes.position,
                attributes.normal,
                attributes.uv};
        }
    };

    struct VertexPositionNormalUvColor final
    {
        DirectX::XMFLOAT3 position{};
        DirectX::XMFLOAT3 normal{};
        DirectX::XMFLOAT2 uv{};
        DirectX::XMFLOAT4 color{};

        [[nodiscard]] static VertexPositionNormalUvColor FromAttributes(
            const VertexAttributes& attributes) noexcept
        {
            return {
                attributes.position,
                attributes.normal,
                attributes.uv,
                attributes.color};
        }
    };

    // A custom vertex type can participate by remaining standard-layout and
    // trivially copyable, and by providing the same FromAttributes function.
    template <typename VertexType>
    concept ShapeVertex =
        std::is_standard_layout_v<VertexType> &&
        std::is_trivially_copyable_v<VertexType> &&
        requires (const VertexAttributes& attributes)
        {
            {
                VertexType::FromAttributes(attributes)
            } noexcept -> std::same_as<VertexType>;
        };

    static_assert(ShapeVertex<VertexPosition>);
    static_assert(ShapeVertex<VertexPositionUv>);
    static_assert(ShapeVertex<VertexPositionColor>);
    static_assert(ShapeVertex<VertexPositionUvColor>);
    static_assert(ShapeVertex<VertexPositionNormal>);
    static_assert(ShapeVertex<VertexPositionNormalUv>);
    static_assert(ShapeVertex<VertexPositionNormalUvColor>);
}
// ===== END Engine\Geometry\Shape\Vertex.h =====

// ===== BEGIN Engine\Geometry\Shape\Shape.h =====


#include <cstddef>
#include <cstdint>
#include <span>
#include <utility>
#include <vector>

namespace mrg::geometry
{
    class Shape
    {
    public:
        virtual ~Shape();

        [[nodiscard]] std::span<const VertexAttributes> Vertices()
            const noexcept;
        [[nodiscard]] std::span<const std::uint32_t> Indices()
            const noexcept;
        [[nodiscard]] std::size_t VertexCount() const noexcept;
        [[nodiscard]] std::size_t IndexCount() const noexcept;

        // Selects the final GPU vertex layout at compile time while preserving
        // the Shape's canonical attributes.
        template <ShapeVertex VertexType>
        [[nodiscard]] std::vector<VertexType> CreateVertices() const
        {
            std::vector<VertexType> result;
            result.reserve(vertices_.size());
            for (const VertexAttributes& attributes : vertices_)
            {
                result.push_back(VertexType::FromAttributes(attributes));
            }
            return result;
        }

    protected:
        Shape() = default;
        Shape(const Shape&) = default;
        Shape& operator=(const Shape&) = default;
        Shape(Shape&&) noexcept = default;
        Shape& operator=(Shape&&) noexcept = default;

        void SetMeshData(
            std::vector<VertexAttributes> vertices,
            std::vector<std::uint32_t> indices);

    private:
        std::vector<VertexAttributes> vertices_;
        std::vector<std::uint32_t> indices_;
    };
}
// ===== END Engine\Geometry\Shape\Shape.h =====

// ===== BEGIN Engine\Geometry\Primitive\RectangleShape.h =====


namespace mrg::geometry
{
    // XY-plane rectangle centered at the origin and facing negative Z.
    class RectangleShape final : public Shape
    {
    public:
        explicit RectangleShape(float width = 2.0F, float height = 2.0F);
    };
}
// ===== END Engine\Geometry\Primitive\RectangleShape.h =====

// ===== BEGIN Engine\Geometry\Primitive\CubeShape.h =====


namespace mrg::geometry
{
    // Cube centered at the origin. Vertices are duplicated per face so each
    // face has an unambiguous normal and complete UV range.
    class CubeShape final : public Shape
    {
    public:
        explicit CubeShape(float sideLength = 2.0F);
    };
}
// ===== END Engine\Geometry\Primitive\CubeShape.h =====

// ===== BEGIN Engine\Geometry\Primitive\SphereShape.h =====


#include <cstdint>

namespace mrg::geometry
{
    class SphereShape final : public Shape
    {
    public:
        explicit SphereShape(
            float radius = 1.0F,
            std::uint32_t sliceCount = 32,
            std::uint32_t stackCount = 16);
    };
}
// ===== END Engine\Geometry\Primitive\SphereShape.h =====

// ===== BEGIN Engine\UI\Core\UiElement.h =====

// Backend-neutral retained-mode UI primitives. Coordinates use a canvas-local
// top-left origin and increase to the right and downward.

#include <cstdint>
#include <memory>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

namespace mrg::ui
{
    using UiElementId = std::uint64_t;

    struct UiPoint
    {
        float x{};
        float y{};
    };

    struct UiSize
    {
        float width{};
        float height{};
    };

    struct UiRect
    {
        float x{};
        float y{};
        float width{};
        float height{};

        [[nodiscard]] bool Contains(UiPoint point) const noexcept;
    };

    struct UiColor
    {
        float red{};
        float green{};
        float blue{};
        float alpha{1.0F};
    };

    struct UiVisualStyle
    {
        UiColor normal{0.20F, 0.22F, 0.27F, 1.0F};
        UiColor hovered{0.28F, 0.32F, 0.40F, 1.0F};
        UiColor pressed{0.12F, 0.16F, 0.24F, 1.0F};
        UiColor disabled{0.14F, 0.14F, 0.16F, 0.65F};
    };

    enum class UiDrawCommandType : std::uint8_t
    {
        Rectangle,
        Text,
    };

    enum class UiTextAlignment : std::uint8_t
    {
        Leading,
        Center,
        Trailing,
    };

    struct UiDrawCommand
    {
        UiDrawCommandType type{UiDrawCommandType::Rectangle};
        UiRect bounds{};
        UiColor color{};
        std::wstring text;
        float fontSize{18.0F};
        UiTextAlignment horizontalAlignment{UiTextAlignment::Leading};
    };

    enum class UiPointerEventType : std::uint8_t
    {
        Enter,
        Leave,
        Move,
        Press,
        Release,
        Click,
    };

    enum class UiPointerButton : std::uint8_t
    {
        None,
        Left,
        Right,
        Middle,
    };

    struct UiPointerEvent
    {
        UiPointerEventType type{};
        UiPointerButton button{UiPointerButton::None};
        UiPoint canvasPosition{};
        UiPoint localPosition{};
        std::int64_t timestampTicks{};
    };

    enum class UiActionType : std::uint8_t
    {
        Clicked,
        ValueChanged,
        SelectionChanged,
    };

    struct UiAction
    {
        UiActionType type{};
        UiElementId source{};
        float value{};
        std::size_t selectedIndex{};
        std::int64_t timestampTicks{};
    };

    class UiCanvas;
    class UiInputRouter;

    class UiElement
    {
    public:
        UiElement();
        virtual ~UiElement();

        UiElement(const UiElement&) = delete;
        UiElement& operator=(const UiElement&) = delete;
        UiElement(UiElement&&) = delete;
        UiElement& operator=(UiElement&&) = delete;

        [[nodiscard]] UiElementId Id() const noexcept;
        [[nodiscard]] const UiRect& Bounds() const noexcept;
        void SetBounds(const UiRect& bounds);
        [[nodiscard]] UiRect BoundsInCanvas() const noexcept;

        [[nodiscard]] bool IsVisible() const noexcept;
        void SetVisible(bool visible) noexcept;
        [[nodiscard]] bool IsEnabled() const noexcept;
        void SetEnabled(bool enabled) noexcept;
        [[nodiscard]] bool IsHitTestVisible() const noexcept;
        void SetHitTestVisible(bool visible) noexcept;
        [[nodiscard]] bool IsHovered() const noexcept;
        [[nodiscard]] bool IsPressed() const noexcept;

        [[nodiscard]] const UiVisualStyle& Style() const noexcept;
        void SetStyle(const UiVisualStyle& style) noexcept;

        [[nodiscard]] UiElement* Parent() noexcept;
        [[nodiscard]] const UiElement* Parent() const noexcept;
        [[nodiscard]] const std::vector<std::unique_ptr<UiElement>>& Children()
            const noexcept;

        UiElement& AddChild(std::unique_ptr<UiElement> child);

        template <typename ElementType, typename... ArgumentTypes>
            requires std::is_base_of_v<UiElement, ElementType>
        ElementType& EmplaceChild(ArgumentTypes&&... arguments)
        {
            auto child = std::make_unique<ElementType>(
                std::forward<ArgumentTypes>(arguments)...);
            ElementType& result = *child;
            AddChild(std::move(child));
            return result;
        }

        [[nodiscard]] bool RemoveChild(UiElementId id) noexcept;

    protected:
        [[nodiscard]] UiColor CurrentBackgroundColor() const noexcept;
        virtual void AppendDrawCommands(
            std::vector<UiDrawCommand>& commands,
            const UiRect& absoluteBounds) const;
        virtual void OnPointerEvent(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions);

    private:
        friend class UiCanvas;
        friend class UiInputRouter;

        struct HitResult
        {
            UiElement* element{};
            UiPoint localPosition{};
        };

        [[nodiscard]] HitResult HitTest(UiPoint parentPosition) noexcept;
        [[nodiscard]] UiElement* Find(UiElementId id) noexcept;
        [[nodiscard]] const UiElement* Find(UiElementId id) const noexcept;
        void CollectDrawCommands(
            std::vector<UiDrawCommand>& commands,
            UiPoint parentOrigin) const;
        void SetHovered(bool hovered) noexcept;
        void SetPressed(bool pressed) noexcept;

        UiElementId id_{};
        UiRect bounds_{};
        UiVisualStyle style_{};
        UiElement* parent_{};
        std::vector<std::unique_ptr<UiElement>> children_;
        bool visible_{true};
        bool enabled_{true};
        bool hitTestVisible_{true};
        bool hovered_{};
        bool pressed_{};
    };
}
// ===== END Engine\UI\Core\UiElement.h =====

// ===== BEGIN Engine\UI\Core\UiCanvas.h =====


#include <span>

namespace mrg::ui
{
    class UiCanvas final
    {
    public:
        explicit UiCanvas(UiSize logicalSize);

        [[nodiscard]] UiSize LogicalSize() const noexcept;
        void SetLogicalSize(UiSize logicalSize);
        [[nodiscard]] UiElement& Root() noexcept;
        [[nodiscard]] const UiElement& Root() const noexcept;
        [[nodiscard]] UiElement* FindElement(UiElementId id) noexcept;
        [[nodiscard]] const UiElement* FindElement(UiElementId id) const noexcept;

        [[nodiscard]] std::vector<UiDrawCommand> BuildDrawList() const;
        [[nodiscard]] std::vector<UiAction> TakeActions();

    private:
        friend class UiInputRouter;

        [[nodiscard]] UiElement::HitResult HitTest(UiPoint position) noexcept;

        UiSize logicalSize_{};
        UiElement root_;
        std::vector<UiAction> actions_;
    };
}
// ===== END Engine\UI\Core\UiCanvas.h =====

// ===== BEGIN Engine\UI\Input\UiInputRouter.h =====


namespace mrg::ui
{
    struct UiPointerInput
    {
        UiPoint position{};
        bool available{true};
        bool leftButtonDown{};
        bool leftButtonPressed{};
        bool leftButtonReleased{};
        std::int64_t timestampTicks{};
    };

    // Converts pointer snapshots into enter/leave/capture/click semantics.
    // Capture keeps a pressed control as the event target until release.
    class UiInputRouter final
    {
    public:
        void Process(UiCanvas& canvas, const UiPointerInput& input);
        void Reset(UiCanvas& canvas) noexcept;

        [[nodiscard]] UiElementId HoveredElement() const noexcept;
        [[nodiscard]] UiElementId CapturedElement() const noexcept;

    private:
        void Dispatch(
            UiCanvas& canvas,
            UiElement& element,
            UiPointerEventType type,
            const UiPointerInput& input,
            UiPointerButton button = UiPointerButton::None);
        void ChangeHovered(
            UiCanvas& canvas,
            UiElement* next,
            const UiPointerInput& input);

        UiElementId hovered_{};
        UiElementId captured_{};
    };
}
// ===== END Engine\UI\Input\UiInputRouter.h =====

// ===== BEGIN Engine\UI\Surface\UiSurface.h =====


#include <DirectXMath.h>

#include <memory>
#include <optional>
#include <vector>

namespace mrg::ui
{
    struct UiSurfaceHit
    {
        float rayParameter{};
        DirectX::XMFLOAT3 worldPosition{};
        DirectX::XMFLOAT3 worldNormal{};
        DirectX::XMFLOAT2 uv{};
    };

    class IUiSurface
    {
    public:
        virtual ~IUiSurface();
        [[nodiscard]] virtual std::optional<UiSurfaceHit> Raycast(
            const collision::Ray3D& worldRay) const noexcept = 0;
    };

    // Finite XY plane. Local UV (0,0) is the upper-left corner, matching the
    // RectangleShape and canvas coordinate convention.
    class PlaneUiSurface final : public IUiSurface
    {
    public:
        PlaneUiSurface(
            float width,
            float height,
            const DirectX::XMFLOAT4X4& worldTransform,
            bool twoSided = false);

        void SetWorldTransform(
            const DirectX::XMFLOAT4X4& worldTransform) noexcept;
        [[nodiscard]] const DirectX::XMFLOAT4X4& WorldTransform()
            const noexcept;
        [[nodiscard]] UiSize WorldSize() const noexcept;
        [[nodiscard]] std::optional<UiSurfaceHit> Raycast(
            const collision::Ray3D& worldRay) const noexcept override;

    private:
        float width_{};
        float height_{};
        DirectX::XMFLOAT4X4 worldTransform_{};
        bool twoSided_{};
    };

    // Copies CPU positions/UVs from a Shape. This O(triangle-count) baseline
    // is intended for modest interactive surfaces; a later BVH can replace
    // the query internally without changing IUiSurface or client code.
    class MeshUvUiSurface final : public IUiSurface
    {
    public:
        MeshUvUiSurface(
            const geometry::Shape& shape,
            const DirectX::XMFLOAT4X4& worldTransform,
            bool twoSided = false);

        void SetWorldTransform(
            const DirectX::XMFLOAT4X4& worldTransform) noexcept;
        [[nodiscard]] const DirectX::XMFLOAT4X4& WorldTransform()
            const noexcept;
        [[nodiscard]] std::optional<UiSurfaceHit> Raycast(
            const collision::Ray3D& worldRay) const noexcept override;

    private:
        struct SurfaceVertex
        {
            DirectX::XMFLOAT3 position{};
            DirectX::XMFLOAT2 uv{};
        };

        std::vector<SurfaceVertex> vertices_;
        std::vector<std::uint32_t> indices_;
        DirectX::XMFLOAT4X4 worldTransform_{};
        bool twoSided_{};
    };

    // Owns a logical Canvas and composes it with a replaceable world surface.
    // It does not inherit UiCanvas because presentation is not UI ownership.
    class WorldSpaceCanvas final
    {
    public:
        WorldSpaceCanvas(
            UiSize logicalSize,
            std::unique_ptr<IUiSurface> surface);

        [[nodiscard]] UiCanvas& Canvas() noexcept;
        [[nodiscard]] const UiCanvas& Canvas() const noexcept;
        [[nodiscard]] IUiSurface& Surface() noexcept;
        [[nodiscard]] const IUiSurface& Surface() const noexcept;
        void SetSurface(std::unique_ptr<IUiSurface> surface);
        [[nodiscard]] std::optional<UiPoint> MapPointer(
            const collision::Ray3D& worldRay) const noexcept;

    private:
        UiCanvas canvas_;
        std::unique_ptr<IUiSurface> surface_;
    };

    [[nodiscard]] std::optional<UiPoint> MapScreenPointer(
        UiPoint screenPosition,
        UiSize viewportSize,
        UiSize canvasSize,
        UiPoint canvasOrigin = {}) noexcept;

    [[nodiscard]] std::optional<collision::Ray3D> CreateWorldPointerRay(
        UiPoint screenPosition,
        UiSize viewportSize,
        const DirectX::XMFLOAT4X4& viewProjection) noexcept;
}
// ===== END Engine\UI\Surface\UiSurface.h =====

// ===== BEGIN Engine\UI\Widget\UiWidgets.h =====


#include <string_view>

namespace mrg::ui
{
    class UiPanel : public UiElement
    {
    public:
        UiPanel() = default;
        ~UiPanel() override = default;
    };

    class UiLabel final : public UiElement
    {
    public:
        explicit UiLabel(std::wstring text = {});

        [[nodiscard]] std::wstring_view Text() const noexcept;
        void SetText(std::wstring text);
        [[nodiscard]] float FontSize() const noexcept;
        void SetFontSize(float fontSize);
        [[nodiscard]] UiColor TextColor() const noexcept;
        void SetTextColor(UiColor color) noexcept;
        void SetHorizontalAlignment(UiTextAlignment alignment) noexcept;

    protected:
        void AppendDrawCommands(
            std::vector<UiDrawCommand>& commands,
            const UiRect& absoluteBounds) const override;

    private:
        std::wstring text_;
        float fontSize_{18.0F};
        UiColor textColor_{1.0F, 1.0F, 1.0F, 1.0F};
        UiTextAlignment alignment_{UiTextAlignment::Leading};
    };

    class UiButton : public UiElement
    {
    public:
        explicit UiButton(std::wstring text = {});

        [[nodiscard]] std::wstring_view Text() const noexcept;
        void SetText(std::wstring text);
        void SetFontSize(float fontSize);

    protected:
        void AppendDrawCommands(
            std::vector<UiDrawCommand>& commands,
            const UiRect& absoluteBounds) const override;
        void OnPointerEvent(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions) override;

        [[nodiscard]] float FontSize() const noexcept;

    private:
        std::wstring text_;
        float fontSize_{17.0F};
    };

    class UiToggle final : public UiButton
    {
    public:
        explicit UiToggle(std::wstring text = {}, bool checked = false);

        [[nodiscard]] bool IsChecked() const noexcept;
        void SetChecked(bool checked) noexcept;

    protected:
        void AppendDrawCommands(
            std::vector<UiDrawCommand>& commands,
            const UiRect& absoluteBounds) const override;
        void OnPointerEvent(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions) override;

    private:
        bool checked_{};
    };

    class UiSlider final : public UiElement
    {
    public:
        explicit UiSlider(float value = 0.0F);

        [[nodiscard]] float Value() const noexcept;
        void SetValue(float value) noexcept;

    protected:
        void AppendDrawCommands(
            std::vector<UiDrawCommand>& commands,
            const UiRect& absoluteBounds) const override;
        void OnPointerEvent(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions) override;

    private:
        void UpdateFromPointer(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions);

        float value_{};
    };

    class UiComboBox final : public UiButton
    {
    public:
        UiComboBox() = default;

        void SetItems(std::vector<std::wstring> items);
        [[nodiscard]] const std::vector<std::wstring>& Items() const noexcept;
        [[nodiscard]] std::size_t SelectedIndex() const noexcept;
        void SetSelectedIndex(std::size_t index);

    protected:
        void OnPointerEvent(
            const UiPointerEvent& event,
            std::vector<UiAction>& actions) override;

    private:
        void RefreshText();

        std::vector<std::wstring> items_;
        std::size_t selectedIndex_{};
    };
}
// ===== END Engine\UI\Widget\UiWidgets.h =====

// ===== BEGIN Engine\Graphics.D3D12\Text\TextRendering.h =====

// DirectWrite-backed text layout with a native D3D12 glyph-atlas renderer.
// Public types intentionally hide DirectWrite objects and atlas resources.

#include <DirectXMath.h>
#include <d3d12.h>

#include <cstdint>
#include <filesystem>
#include <memory>
#include <string_view>

namespace mrg::graphics
{
    enum class TextHorizontalAlignment : std::uint8_t
    {
        Leading,
        Center,
        Trailing,
    };

    enum class TextVerticalAlignment : std::uint8_t
    {
        Near,
        Center,
        Far,
    };

    class Font final
    {
    public:
        ~Font();

        Font(const Font&) = delete;
        Font& operator=(const Font&) = delete;

        [[nodiscard]] std::wstring_view FamilyName() const noexcept;

    private:
        friend class TextRenderSystem;
        struct Impl;

        explicit Font(std::shared_ptr<Impl> implementation);
        std::shared_ptr<Impl> implementation_;
    };

    using FontHandle = std::shared_ptr<const Font>;

    struct TextStyle
    {
        FontHandle font;
        float fontSizePixels{20.0F};
        DirectX::XMFLOAT4 color{1.0F, 1.0F, 1.0F, 1.0F};
    };

    struct TextDrawCommand
    {
        DirectX::XMFLOAT2 positionPixels{};
        DirectX::XMFLOAT2 layoutSizePixels{512.0F, 128.0F};
        TextHorizontalAlignment horizontalAlignment{
            TextHorizontalAlignment::Leading};
        TextVerticalAlignment verticalAlignment{
            TextVerticalAlignment::Near};
        TextStyle style{};
    };

    // Text is submitted while a RenderContext is open. Submit performs
    // DirectWrite layout and records CPU-side glyph instances only; Flush
    // uploads cache misses and emits batched D3D12 draws at EndFrame.
    class TextRenderSystem final
    {
    public:
        static constexpr std::uint32_t FrameCount = 2;

        TextRenderSystem();
        ~TextRenderSystem();

        TextRenderSystem(const TextRenderSystem&) = delete;
        TextRenderSystem& operator=(const TextRenderSystem&) = delete;

        void Initialize(
            ID3D12Device& device,
            DXGI_FORMAT renderTargetFormat);
        void Shutdown() noexcept;

        [[nodiscard]] FontHandle LoadSystemFont(
            std::wstring_view familyName);
        [[nodiscard]] FontHandle LoadFontFile(
            const std::filesystem::path& fontFile);

        void BeginFrame(std::uint32_t frameIndex);
        void Submit(
            std::wstring_view text,
            const TextDrawCommand& command);
        void Flush(
            ID3D12GraphicsCommandList& commandList,
            std::uint32_t viewportWidth,
            std::uint32_t viewportHeight);

    private:
        struct Impl;
        std::unique_ptr<Impl> implementation_;
    };
}
// ===== END Engine\Graphics.D3D12\Text\TextRendering.h =====

// ===== BEGIN Engine\Graphics.D3D12\Texture\TextureManager.h =====

// Texture feature: WIC decoding, uploads, and SRV descriptor sets.

#include <DirectXMath.h>
#include <d3d12.h>
#include <wrl/client.h>

#include <cstdint>
#include <filesystem>
#include <memory>
#include <span>
#include <vector>

namespace mrg::graphics
{
    // One descriptor table reserves this many entries.  Each entry can point
    // at an independently sized Texture2D resource; this is not a
    // D3D12 Texture2DArray and therefore does not require equal dimensions.
    inline constexpr std::uint32_t MaxTexturesPerSet = 64;

    struct TextureInfo final
    {
        std::uint32_t width{};
        std::uint32_t height{};
    };

    struct UvTransform final
    {
        DirectX::XMFLOAT2 scale{1.0F, 1.0F};
        DirectX::XMFLOAT2 offset{0.0F, 0.0F};
    };

    class TextureSet final
    {
    public:
        TextureSet(const TextureSet&) = delete;
        TextureSet& operator=(const TextureSet&) = delete;

        [[nodiscard]] std::size_t Size() const noexcept;
        [[nodiscard]] const TextureInfo& Info(std::size_t index) const;

        // Returns a centered "cover" transform.  Sampling a rectangular
        // image on the requested aspect ratio crops the excess dimension,
        // filling the complete target without stretching or letterboxing.
        [[nodiscard]] UvTransform MakeCoverUvTransform(
            std::size_t index,
            float targetAspectRatio = 1.0F) const;

    private:
        friend class MeshRenderSystem;
        friend class TextureManager;

        TextureSet() = default;

        std::vector<TextureInfo> textureInfo_;
        std::vector<Microsoft::WRL::ComPtr<ID3D12Resource>> resources_;
        D3D12_GPU_DESCRIPTOR_HANDLE gpuDescriptorStart_{};
    };

    using TextureSetHandle = std::shared_ptr<const TextureSet>;

    // Decodes common image formats through WIC and owns the shader-visible
    // descriptor heap used by textured materials.  Initial uploads are
    // synchronous so temporary upload buffers can be released immediately;
    // no upload wait is added to the normal render loop.
    class TextureManager final
    {
    public:
        TextureManager() = default;
        ~TextureManager();

        TextureManager(const TextureManager&) = delete;
        TextureManager& operator=(const TextureManager&) = delete;

        void Initialize(
            ID3D12Device& device,
            ID3D12CommandQueue& commandQueue);
        void Shutdown() noexcept;

        [[nodiscard]] TextureSetHandle LoadTextureSet(
            std::span<const std::filesystem::path> paths);

        [[nodiscard]] ID3D12DescriptorHeap* DescriptorHeap() const noexcept;

    private:
        struct DecodedImage;

        void ValidateTextureSetRequest(
            std::span<const std::filesystem::path> paths) const;
        [[nodiscard]] static DecodedImage DecodeImage(
            const std::filesystem::path& path);
        void BeginUploadCommands();
        [[nodiscard]] D3D12_CPU_DESCRIPTOR_HANDLE
            InitializeDescriptorBlock(TextureSet& textureSet);
        void RecordTextureUpload(
            const DecodedImage& image,
            std::size_t descriptorIndex,
            D3D12_CPU_DESCRIPTOR_HANDLE descriptorBlockStart,
            TextureSet& textureSet,
            std::vector<Microsoft::WRL::ComPtr<ID3D12Resource>>&
                uploadBuffers);
        void ExecuteUploadAndWait();

        ID3D12Device* device_{};
        ID3D12CommandQueue* commandQueue_{};
        Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> descriptorHeap_;
        Microsoft::WRL::ComPtr<ID3D12CommandAllocator> uploadAllocator_;
        Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> uploadCommandList_;
        Microsoft::WRL::ComPtr<ID3D12Fence> uploadFence_;
        HANDLE uploadFenceEvent_{};
        std::uint64_t nextUploadFenceValue_{1};
        std::uint32_t descriptorSize_{};
        std::uint32_t nextDescriptorBlock_{};
        bool initialized_{};
    };
}
// ===== END Engine\Graphics.D3D12\Texture\TextureManager.h =====

// ===== BEGIN Engine\Graphics.D3D12\Mesh\MeshRendering.h =====


#include <DirectXMath.h>
#include <d3d12.h>
#include <wrl/client.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <limits>
#include <span>
#include <type_traits>
#include <vector>

namespace mrg::graphics
{
    inline constexpr std::uint32_t NoTextureIndex =
        std::numeric_limits<std::uint32_t>::max();

    enum class MeshVertexLayout : std::uint8_t
    {
        Unsupported,
        Position,
        PositionUv,
        PositionColor,
        PositionUvColor,
        PositionNormal,
        PositionNormalUv,
        PositionNormalUvColor,
    };

    template <typename VertexType>
    inline constexpr MeshVertexLayout MeshVertexLayoutFor =
        MeshVertexLayout::Unsupported;

    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPosition> =
            MeshVertexLayout::Position;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionUv> =
            MeshVertexLayout::PositionUv;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionColor> =
            MeshVertexLayout::PositionColor;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionUvColor> =
            MeshVertexLayout::PositionUvColor;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionNormal> =
            MeshVertexLayout::PositionNormal;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionNormalUv> =
            MeshVertexLayout::PositionNormalUv;
    template <>
    inline constexpr MeshVertexLayout
        MeshVertexLayoutFor<geometry::VertexPositionNormalUvColor> =
            MeshVertexLayout::PositionNormalUvColor;

    // Immutable GPU copy of one Shape.  Geometry remains CPU/backend-neutral;
    // this object exclusively owns the D3D12 vertex and index resources.
    class GpuMesh final
    {
    public:
        GpuMesh(const GpuMesh&) = delete;
        GpuMesh& operator=(const GpuMesh&) = delete;

        [[nodiscard]] MeshVertexLayout VertexLayout() const noexcept;
        [[nodiscard]] std::uint32_t IndexCount() const noexcept;

    private:
        friend class MeshRenderSystem;

        GpuMesh() = default;

        Microsoft::WRL::ComPtr<ID3D12Resource> vertexBuffer_;
        Microsoft::WRL::ComPtr<ID3D12Resource> indexBuffer_;
        D3D12_VERTEX_BUFFER_VIEW vertexBufferView_{};
        D3D12_INDEX_BUFFER_VIEW indexBufferView_{};
        MeshVertexLayout vertexLayout_{MeshVertexLayout::Unsupported};
        std::uint32_t indexCount_{};
    };

    using GpuMeshHandle = std::shared_ptr<const GpuMesh>;

    enum class BuiltInMaterial : std::uint8_t
    {
        UnlitVertexColor,
        UnlitVertexColorTextureArray,
    };

    // Shared shader/root-signature/PSO definition.  Instances refer to this
    // immutable template so expensive pipeline objects are created once.
    class MaterialTemplate final
    {
    public:
        MaterialTemplate(const MaterialTemplate&) = delete;
        MaterialTemplate& operator=(const MaterialTemplate&) = delete;

        [[nodiscard]] BuiltInMaterial Type() const noexcept;
        [[nodiscard]] MeshVertexLayout RequiredVertexLayout() const noexcept;

    private:
        friend class MaterialInstance;
        friend class MeshRenderSystem;

        MaterialTemplate() = default;

        BuiltInMaterial type_{BuiltInMaterial::UnlitVertexColor};
        MeshVertexLayout requiredVertexLayout_{
            MeshVertexLayout::PositionColor};
        bool usesTextureSet_{};
        Microsoft::WRL::ComPtr<ID3D12RootSignature> rootSignature_;
        Microsoft::WRL::ComPtr<ID3D12PipelineState> pipelineState_;
    };

    using MaterialTemplateHandle = std::shared_ptr<const MaterialTemplate>;

    // Per-material binding object.  A textured instance retains its
    // TextureSet so the SRV descriptors and underlying resources remain valid
    // across every in-flight frame.
    class MaterialInstance final
    {
    public:
        MaterialInstance(const MaterialInstance&) = delete;
        MaterialInstance& operator=(const MaterialInstance&) = delete;

        [[nodiscard]] const MaterialTemplateHandle& Template() const noexcept;
        void SetTextureSet(TextureSetHandle textureSet);
        [[nodiscard]] const TextureSetHandle& Textures() const noexcept;

    private:
        friend class MeshRenderSystem;

        explicit MaterialInstance(MaterialTemplateHandle materialTemplate);

        MaterialTemplateHandle materialTemplate_;
        TextureSetHandle textureSet_;
    };

    using MaterialInstanceHandle = std::shared_ptr<MaterialInstance>;

    // Owns common material pipelines, uploads Shape data, batches submitted
    // mesh instances, and records DrawIndexedInstanced calls.
    class MeshRenderSystem final
    {
    public:
        static constexpr std::uint32_t FrameCount = 2;

        MeshRenderSystem() = default;
        ~MeshRenderSystem();

        MeshRenderSystem(const MeshRenderSystem&) = delete;
        MeshRenderSystem& operator=(const MeshRenderSystem&) = delete;

        void Initialize(
            ID3D12Device& device,
            ID3D12CommandQueue& commandQueue,
            DXGI_FORMAT renderTargetFormat,
            DXGI_FORMAT depthStencilFormat);
        void Shutdown() noexcept;

        template <geometry::ShapeVertex VertexType>
        [[nodiscard]] GpuMeshHandle CreateMesh(
            const geometry::Shape& shape)
        {
            constexpr MeshVertexLayout layout =
                MeshVertexLayoutFor<std::remove_cv_t<VertexType>>;
            static_assert(
                layout != MeshVertexLayout::Unsupported,
                "Register this vertex type with MeshVertexLayoutFor before "
                "uploading it.");

            const std::vector<VertexType> vertices =
                shape.CreateVertices<VertexType>();
            const std::span<const VertexType> vertexSpan{
                vertices.data(),
                vertices.size()};
            return CreateMeshData(
                std::as_bytes(vertexSpan),
                sizeof(VertexType),
                layout,
                shape.Indices());
        }

        [[nodiscard]] MaterialInstanceHandle CreateMaterial(
            BuiltInMaterial material);
        [[nodiscard]] TextureManager& Textures() noexcept;
        [[nodiscard]] const TextureManager& Textures() const noexcept;

        // Called by D3D12Renderer after the selected frame resource is safe.
        void BeginFrame(std::uint32_t frameIndex);

        // Stores CPU-side instance data only.  Flush sorts equal mesh/material
        // pairs and records one instanced draw for each batch.
        void Submit(
            GpuMeshHandle mesh,
            MaterialInstanceHandle material,
            const DirectX::XMFLOAT4X4& world,
            const DirectX::XMFLOAT4X4& viewProjection,
            const DirectX::XMFLOAT4& color,
            const DirectX::XMFLOAT2& uvScale,
            const DirectX::XMFLOAT2& uvOffset,
            std::uint32_t textureIndex);

        void Flush(ID3D12GraphicsCommandList& commandList);

    private:
        struct InstanceData
        {
            DirectX::XMFLOAT4X4 worldViewProjection{};
            DirectX::XMFLOAT4 color{1.0F, 1.0F, 1.0F, 1.0F};
            DirectX::XMFLOAT4 uvTransform{1.0F, 1.0F, 0.0F, 0.0F};
            std::uint32_t textureIndex{NoTextureIndex};
            std::array<std::uint32_t, 3> padding{};
        };

        struct PendingItem
        {
            GpuMeshHandle mesh;
            MaterialInstanceHandle material;
            InstanceData instance;
        };

        struct FrameInstanceBuffer
        {
            Microsoft::WRL::ComPtr<ID3D12Resource> resource;
            std::byte* mappedData{};
            std::size_t capacity{};
            // A scene may be destroyed immediately after it submits a frame.
            // Keep the referenced GPU objects alive until this frame index is
            // selected again after D3D12Renderer's fence wait.
            std::vector<GpuMeshHandle> retainedMeshes;
            std::vector<MaterialInstanceHandle> retainedMaterials;
        };

        [[nodiscard]] GpuMeshHandle CreateMeshData(
            std::span<const std::byte> vertexBytes,
            std::size_t vertexStrideBytes,
            MeshVertexLayout layout,
            std::span<const std::uint32_t> indices);
        [[nodiscard]] std::shared_ptr<MaterialTemplate>
            CreateUnlitVertexColorTemplate();
        [[nodiscard]] std::shared_ptr<MaterialTemplate>
            CreateUnlitVertexColorTextureArrayTemplate();
        void SortPendingItems();
        void UploadPendingInstances(FrameInstanceBuffer& instanceBuffer);
        [[nodiscard]] std::size_t FindBatchEnd(
            std::size_t batchStart) const noexcept;
        void DrawBatch(
            ID3D12GraphicsCommandList& commandList,
            const FrameInstanceBuffer& instanceBuffer,
            std::size_t batchStart,
            std::size_t batchEnd);
        void EnsureInstanceCapacity(
            std::uint32_t frameIndex,
            std::size_t requiredInstanceCount);

        ID3D12Device* device_{};
        DXGI_FORMAT renderTargetFormat_{DXGI_FORMAT_R8G8B8A8_UNORM};
        DXGI_FORMAT depthStencilFormat_{DXGI_FORMAT_D32_FLOAT};
        std::shared_ptr<MaterialTemplate> unlitVertexColorTemplate_;
        std::shared_ptr<MaterialTemplate>
            unlitVertexColorTextureArrayTemplate_;
        TextureManager textureManager_;
        std::array<FrameInstanceBuffer, FrameCount> instanceBuffers_{};
        std::vector<PendingItem> pendingItems_;
        std::uint32_t currentFrameIndex_{};
        bool initialized_{};
        bool frameOpen_{};
    };
}
// ===== END Engine\Graphics.D3D12\Mesh\MeshRendering.h =====

// ===== BEGIN Engine\Graphics.D3D12\Renderer\D3D12Renderer.h =====

// Renderer feature: D3D12 device, frame resources, and presentation.

#include <Windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <wrl/client.h>

#include <array>
#include <cstdint>
#include <memory>

namespace mrg::graphics
{
    class MeshRenderSystem;
    class TextRenderSystem;

    struct ClearColor
    {
        float red{};
        float green{};
        float blue{};
        float alpha{1.0F};
    };

    struct RenderContext
    {
        ID3D12GraphicsCommandList* commandList{};
        D3D12_VIEWPORT viewport{};
        D3D12_RECT scissorRectangle{};
        std::uint32_t width{};
        std::uint32_t height{};
        std::uint32_t frameIndex{};
        DXGI_FORMAT renderTargetFormat{DXGI_FORMAT_R8G8B8A8_UNORM};
        DXGI_FORMAT depthStencilFormat{DXGI_FORMAT_D32_FLOAT};
        // Non-owning queue/service for high-level mesh submissions during
        // this BeginFrame/EndFrame pair.
        MeshRenderSystem* meshRendering{};
        // Non-owning queue/service for screen-space text submissions.
        TextRenderSystem* textRendering{};
    };

    // Public D3D12 frame lifecycle, device, and presentation service.
    // Initialize creates the persistent device/swap-chain objects.  Each
    // BeginFrame/EndFrame pair records and submits one back-buffer frame;
    // FrameCount allocators and fences prevent reuse while the GPU owns them.
    class D3D12Renderer final
    {
    public:
        static constexpr std::uint32_t FrameCount = 2;

        D3D12Renderer() = default;
        ~D3D12Renderer();

        D3D12Renderer(const D3D12Renderer&) = delete;
        D3D12Renderer& operator=(const D3D12Renderer&) = delete;

        void Initialize(
            HWND window,
            std::uint32_t width,
            std::uint32_t height);
        void Resize(std::uint32_t width, std::uint32_t height);

        // Opens a command list, transitions/clears the current back buffer,
        // and returns the recording context for Client rendering.
        [[nodiscard]] RenderContext BeginFrame(const ClearColor& clearColor);
        // Closes/submits that list, presents without VSync, and marks the
        // current frame resource with the fence value that protects it.
        void EndFrame();
        void WaitForGpu();

        [[nodiscard]] ID3D12Device* Device() const noexcept;
        [[nodiscard]] MeshRenderSystem& MeshRendering() const noexcept;
        [[nodiscard]] TextRenderSystem& TextRendering() const noexcept;
        [[nodiscard]] DXGI_FORMAT RenderTargetFormat() const noexcept;
        [[nodiscard]] DXGI_FORMAT DepthStencilFormat() const noexcept;
        [[nodiscard]] bool SupportsTearing() const noexcept;

    private:
        void CreateDeviceAndFactory();
        void CreateCommandObjects();
        void CreateSwapChain(HWND window);
        void CreateDescriptorHeaps();
        void CreateRenderTargets();
        void CreateDepthStencil();
        void UpdateViewport() noexcept;
        void WaitForFrame(std::uint32_t frameIndex);

        HWND window_{};
        std::uint32_t width_{};
        std::uint32_t height_{};
        std::uint32_t frameIndex_{};
        std::uint32_t rtvDescriptorSize_{};
        bool tearingSupported_{};
        bool frameOpen_{};

        DXGI_FORMAT renderTargetFormat_{DXGI_FORMAT_R8G8B8A8_UNORM};
        DXGI_FORMAT depthStencilFormat_{DXGI_FORMAT_D32_FLOAT};
        D3D12_VIEWPORT viewport_{};
        D3D12_RECT scissorRectangle_{};

        Microsoft::WRL::ComPtr<IDXGIFactory6> factory_;
        Microsoft::WRL::ComPtr<ID3D12Device> device_;
        Microsoft::WRL::ComPtr<ID3D12CommandQueue> commandQueue_;
        Microsoft::WRL::ComPtr<IDXGISwapChain4> swapChain_;
        Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> rtvHeap_;
        Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> dsvHeap_;
        std::array<Microsoft::WRL::ComPtr<ID3D12Resource>, FrameCount>
            renderTargets_{};
        Microsoft::WRL::ComPtr<ID3D12Resource> depthStencil_;
        std::array<Microsoft::WRL::ComPtr<ID3D12CommandAllocator>, FrameCount>
            commandAllocators_{};
        Microsoft::WRL::ComPtr<ID3D12GraphicsCommandList> commandList_;
        Microsoft::WRL::ComPtr<ID3D12Fence> fence_;
        std::array<std::uint64_t, FrameCount> frameFenceValues_{};
        std::uint64_t nextFenceValue_{1};
        HANDLE fenceEvent_{};
        std::unique_ptr<MeshRenderSystem> meshRenderSystem_;
        std::unique_ptr<TextRenderSystem> textRenderSystem_;
    };
}
// ===== END Engine\Graphics.D3D12\Renderer\D3D12Renderer.h =====

// ===== BEGIN Engine\Graphics.D3D12\UI\UiRendering.h =====

// D3D12 presentation adapter for backend-neutral UiCanvas draw commands.


#include <DirectXMath.h>

namespace mrg::graphics
{
    class D3D12UiRenderer final
    {
    public:
        D3D12UiRenderer() = default;

        void Initialize(
            MeshRenderSystem& meshRendering,
            TextRenderSystem& textRendering);
        void Shutdown() noexcept;

        // Renders at pixel size with a top-left screen origin. Text is
        // supported by the existing DirectWrite-backed screen renderer.
        void SubmitScreen(
            const ui::UiCanvas& canvas,
            const RenderContext& context,
            ui::UiPoint screenOrigin = {});

        // Renders rectangles directly onto a finite local XY plane. The
        // transform positions that plane in the world. Rich text and curved
        // visual warping require a canvas-to-texture presenter; input mapping
        // remains fully supported by PlaneUiSurface/MeshUvUiSurface.
        void SubmitPlane(
            const ui::UiCanvas& canvas,
            const RenderContext& context,
            const DirectX::XMFLOAT4X4& surfaceWorld,
            ui::UiSize surfaceWorldSize,
            const DirectX::XMFLOAT4X4& viewProjection);

    private:
        [[nodiscard]] bool IsInitialized() const noexcept;

        MeshRenderSystem* meshRendering_{};
        TextRenderSystem* textRendering_{};
        GpuMeshHandle rectangleMesh_;
        MaterialInstanceHandle rectangleMaterial_;
        FontHandle defaultFont_;
    };
}
// ===== END Engine\Graphics.D3D12\UI\UiRendering.h =====

// ===== BEGIN Engine\Core\Client\IGameClient.h =====


#include <cstdint>
#include <filesystem>
#include <string>

namespace mrg
{
    struct PerformanceOverlayConfig
    {
        // Relative paths are resolved from the executable directory. Empty
        // paths use the corresponding installed system-font family.
        std::filesystem::path framesPerSecondFontFile;
        std::filesystem::path updatesPerSecondFontFile;
        std::wstring framesPerSecondSystemFont{L"Consolas"};
        std::wstring updatesPerSecondSystemFont{L"Segoe UI"};
        float framesPerSecondFontSizePixels{18.0F};
        float updatesPerSecondFontSizePixels{22.0F};
        DirectX::XMFLOAT4 framesPerSecondColor{
            0.10F,
            0.40F,
            0.95F,
            1.0F};
        DirectX::XMFLOAT4 updatesPerSecondColor{
            0.95F,
            0.25F,
            0.12F,
            1.0F};
        float layoutWidthPixels{360.0F};
        float rightMarginPixels{20.0F};
        float bottomMarginPixels{18.0F};
        float lineGapPixels{4.0F};
        // Intended for automated hidden rendering checks. Interactive games
        // normally leave this false and use F1 to toggle the overlay.
        bool initiallyVisible{};
    };

    // Returned before any runtime subsystem exists. It lets the Client
    // describe the window, scheduling, and audio requirements to Run.
    struct EngineConfig
    {
        std::wstring windowTitle{L"My Rhythm Game"};
        std::uint32_t windowWidth{1280};
        std::uint32_t windowHeight{720};
        graphics::ClearColor clearColor{
            240.0F / 255.0F,
            248.0F / 255.0F,
            1.0F,
            1.0F};

        audio::AudioConfig audio{};
        audio::AudioBackendFactory audioBackendFactory{};
        double audioUpdateRateHz{500.0};
        double renderRateOverrideHz{};
        double maximumUpdateDeltaSeconds{0.1};
        PerformanceOverlayConfig performanceOverlay{};

        bool showWindow{true};
        std::uint64_t autoExitAfterRenderedFrames{};
    };

    // Non-owning services created by Run. They remain valid from Initialize
    // through the start of Shutdown; Client code must not release them or
    // retain them after Shutdown.
    struct EngineServices
    {
        graphics::MeshRenderSystem& meshRendering;
        graphics::TextRenderSystem& textRendering;
        audio::AudioSystem& audio;
        std::uint32_t windowWidth{};
        std::uint32_t windowHeight{};
    };

    // One Update invocation. deltaSeconds is QPC-derived and clamped by
    // EngineConfig. Input carries both current state and ordered Raw Input
    // events with their original QPC timestamps.
    struct UpdateContext
    {
        double deltaSeconds{};
        double totalSeconds{};
        std::uint64_t updateIndex{};
        const platform::InputState& input;
        audio::AudioSystem& audio;
    };

    // Contract implemented by a game-specific Client project.
    // Normal lifecycle: GetEngineConfig -> Initialize ->
    // [Update / Render / OnResize]* -> Shutdown.
    class IGameClient
    {
    public:
        virtual ~IGameClient();

        [[nodiscard]] virtual EngineConfig GetEngineConfig() const = 0;
        virtual void Initialize(const EngineServices& services) = 0;
        [[nodiscard]] virtual bool Update(const UpdateContext& context) = 0;
        virtual void Render(const graphics::RenderContext& context) = 0;
        virtual void OnResize(std::uint32_t width, std::uint32_t height) = 0;
        virtual void Shutdown() noexcept = 0;
    };
}
// ===== END Engine\Core\Client\IGameClient.h =====

// ===== BEGIN Engine\Core\System\HighResolutionClock.h =====

#include <cstdint>

namespace mrg::system
{
    // General-purpose QueryPerformanceCounter clock used by the engine loop.
    class HighResolutionClock final
    {
    public:
        HighResolutionClock();

        [[nodiscard]] double Tick(double& totalSeconds) noexcept;
        [[nodiscard]] double NowSeconds() const noexcept;

    private:
        double inverseFrequency_{};
        std::int64_t startCounter_{};
        double previousSeconds_{};
    };
}
// ===== END Engine\Core\System\HighResolutionClock.h =====

// ===== BEGIN Engine\Core\System\Camera.h =====

// System feature: backend-neutral view and projection matrices.

#include <DirectXMath.h>

#include <cstdint>

namespace mrg::scene
{
    enum class CameraProjectionType : std::uint8_t
    {
        Perspective,
        Orthographic,
    };

    // Backend-neutral, left-handed camera state for 3D and 2D scenes.
    // Position/yaw/pitch produce the view matrix.  Select Perspective for a
    // FOV-based 3D camera or Orthographic for a 2D-style size-based camera.
    class Camera final
    {
    public:
        Camera() = default;

        void SetPosition(float x, float y, float z) noexcept;
        void SetPosition(const DirectX::XMFLOAT3& position) noexcept;
        [[nodiscard]] const DirectX::XMFLOAT3& Position() const noexcept;

        // Angles are radians.  Pitch is clamped short of +/- pi/2 so the
        // forward vector never becomes parallel to the world-up vector.
        void SetYawPitchRadians(float yawRadians, float pitchRadians) noexcept;
        void AddYawPitchRadians(
            float yawDeltaRadians,
            float pitchDeltaRadians) noexcept;
        [[nodiscard]] float YawRadians() const noexcept;
        [[nodiscard]] float PitchRadians() const noexcept;

        [[nodiscard]] DirectX::XMFLOAT3 Forward() const noexcept;
        [[nodiscard]] DirectX::XMFLOAT3 Right() const noexcept;
        [[nodiscard]] DirectX::XMFLOAT3 Up() const noexcept;

        // Perspective arguments are vertical FOV in radians, aspect ratio,
        // and positive near/far planes.  This also selects Perspective mode.
        void SetPerspective(
            float verticalFieldOfViewRadians,
            float aspectRatio,
            float nearPlane,
            float farPlane);
        void SetVerticalFieldOfViewRadians(float fieldOfViewRadians);
        void SetPerspectiveAspectRatio(float aspectRatio);

        // Orthographic width/height define the visible world size.  It is
        // suitable for 2D rendering; use SetOrthographicSize on resize when
        // the logical 2D viewport should follow the window dimensions.
        void SetOrthographic(
            float width,
            float height,
            float nearPlane,
            float farPlane);
        void SetOrthographicSize(float width, float height);
        void SetDepthRange(float nearPlane, float farPlane);

        [[nodiscard]] CameraProjectionType ProjectionType() const noexcept;
        [[nodiscard]] float VerticalFieldOfViewRadians() const noexcept;
        [[nodiscard]] float PerspectiveAspectRatio() const noexcept;
        [[nodiscard]] float OrthographicWidth() const noexcept;
        [[nodiscard]] float OrthographicHeight() const noexcept;
        [[nodiscard]] float NearPlane() const noexcept;
        [[nodiscard]] float FarPlane() const noexcept;

        [[nodiscard]] DirectX::XMMATRIX ViewMatrix() const noexcept;
        [[nodiscard]] DirectX::XMMATRIX ProjectionMatrix() const noexcept;
        [[nodiscard]] DirectX::XMMATRIX ViewProjectionMatrix() const noexcept;

    private:
        [[nodiscard]] static float ClampPitch(float pitchRadians) noexcept;

        DirectX::XMFLOAT3 position_{};
        float yawRadians_{};
        float pitchRadians_{};
        CameraProjectionType projectionType_{CameraProjectionType::Perspective};
        float verticalFieldOfViewRadians_{DirectX::XM_PI / 3.0F};
        float perspectiveAspectRatio_{1.0F};
        float orthographicWidth_{1.0F};
        float orthographicHeight_{1.0F};
        float nearPlane_{0.1F};
        float farPlane_{1000.0F};
    };
}
// ===== END Engine\Core\System\Camera.h =====

// ===== BEGIN Engine\Core\System\TransformNode.h =====

// System feature: reusable hierarchical local and world transforms.

#include <DirectXMath.h>

#include <memory>
#include <vector>

namespace mrg::scene
{
    // Public hierarchical local/world transform used by Client scene objects.
    class TransformNode final
    {
    public:
        TransformNode();

        TransformNode(const TransformNode&) = delete;
        TransformNode& operator=(const TransformNode&) = delete;

        void SetPosition(float x, float y, float z) noexcept;
        void SetScale(float x, float y, float z) noexcept;
        void SetRotationRollPitchYaw(
            float pitch,
            float yaw,
            float roll) noexcept;
        void SetRotationQuaternion(
            float x,
            float y,
            float z,
            float w) noexcept;

        [[nodiscard]] const DirectX::XMFLOAT3& Position() const noexcept;
        [[nodiscard]] const DirectX::XMFLOAT3& Scale() const noexcept;
        [[nodiscard]] const DirectX::XMFLOAT4& Rotation() const noexcept;

        TransformNode& AddChild(std::unique_ptr<TransformNode> child);
        [[nodiscard]] TransformNode& CreateChild();
        [[nodiscard]] TransformNode* Parent() const noexcept;
        [[nodiscard]] const std::vector<std::unique_ptr<TransformNode>>&
            Children() const noexcept;

        [[nodiscard]] const DirectX::XMFLOAT4X4& WorldMatrix();
        void UpdateWorldRecursive();

    private:
        void MarkWorldDirty() noexcept;
        void UpdateWorld();

        DirectX::XMFLOAT3 position_{0.0F, 0.0F, 0.0F};
        DirectX::XMFLOAT3 scale_{1.0F, 1.0F, 1.0F};
        DirectX::XMFLOAT4 rotation_{0.0F, 0.0F, 0.0F, 1.0F};
        DirectX::XMFLOAT4X4 world_{};
        TransformNode* parent_{};
        std::vector<std::unique_ptr<TransformNode>> children_;
        bool worldDirty_{true};
    };
}
// ===== END Engine\Core\System\TransformNode.h =====

// ===== BEGIN Engine\Core\App\Engine.h =====


#include <memory>

namespace mrg
{
    // Takes exclusive ownership of the Client and runs the complete engine
    // lifetime.  See Docs/ExecutionFlow.md for the detailed call order.
    int Run(std::unique_ptr<IGameClient> client);
}
// ===== END Engine\Core\App\Engine.h =====

// ===== BEGIN Engine\Core\Scene\GameScene.h =====


#include <cstdint>

namespace mrg::scene
{
    class SceneManager;

    // Base lifecycle for one switchable Client scene.
    class GameScene
    {
    public:
        virtual ~GameScene();

        // Called once per object, when its registered route is first entered.
        // DestroyOnExit routes create a fresh object on every entry, so each
        // new object receives its own Initialize/Shutdown pair.
        virtual void Initialize(const EngineServices& services);

        // Called every time this scene becomes or ceases to be active.
        virtual void BeginScene();
        virtual void EndScene() noexcept;

        virtual void OnResize(std::uint32_t width, std::uint32_t height);
        virtual void Update(
            const UpdateContext& context,
            SceneManager& scenes) = 0;
        virtual void Render(const graphics::RenderContext& context) = 0;

        // Called once before the manager releases the scene. Renderer frame
        // resources retain submitted GPU handles until their fences complete.
        virtual void Shutdown() noexcept;
    };
}
// ===== END Engine\Core\Scene\GameScene.h =====

// ===== BEGIN Engine\Core\System\MeshInstance.h =====


#include <DirectXMath.h>

#include <cstdint>

namespace mrg::scene
{
    // Reusable wrapper that combines one GPU mesh, one material,
    // and per-instance state.  Shape itself stays renderer-independent.
    class MeshInstance final
    {
    public:
        MeshInstance() = default;
        MeshInstance(
            graphics::GpuMeshHandle mesh,
            graphics::MaterialInstanceHandle material);

        void SetMesh(graphics::GpuMeshHandle mesh);
        void SetMaterial(graphics::MaterialInstanceHandle material);
        void Reset() noexcept;
        [[nodiscard]] const graphics::GpuMeshHandle& Mesh() const noexcept;
        [[nodiscard]] const graphics::MaterialInstanceHandle&
            Material() const noexcept;

        [[nodiscard]] TransformNode& Transform() noexcept;
        [[nodiscard]] const TransformNode& Transform() const noexcept;

        void SetColor(const DirectX::XMFLOAT4& color) noexcept;
        [[nodiscard]] const DirectX::XMFLOAT4& Color() const noexcept;
        void SetTextureIndex(std::uint32_t textureIndex) noexcept;
        void ClearTexture() noexcept;
        [[nodiscard]] std::uint32_t TextureIndex() const noexcept;
        void SetUvTransform(
            const DirectX::XMFLOAT2& scale,
            const DirectX::XMFLOAT2& offset) noexcept;
        void SetUvTransform(
            const graphics::UvTransform& transform) noexcept;
        [[nodiscard]] const DirectX::XMFLOAT2& UvScale() const noexcept;
        [[nodiscard]] const DirectX::XMFLOAT2& UvOffset() const noexcept;
        [[nodiscard]] bool IsReady() const noexcept;

        // Queues this instance; D3D12Renderer batches matching mesh/material
        // pairs and performs DrawIndexedInstanced in EndFrame.
        void Submit(
            const graphics::RenderContext& context,
            const Camera& camera);

    private:
        graphics::GpuMeshHandle mesh_;
        graphics::MaterialInstanceHandle material_;
        TransformNode transform_;
        DirectX::XMFLOAT4 color_{1.0F, 1.0F, 1.0F, 1.0F};
        DirectX::XMFLOAT2 uvScale_{1.0F, 1.0F};
        DirectX::XMFLOAT2 uvOffset_{0.0F, 0.0F};
        std::uint32_t textureIndex_{graphics::NoTextureIndex};
    };
}
// ===== END Engine\Core\System\MeshInstance.h =====

// ===== BEGIN Engine\Core\Scene\SceneManager.h =====


#include <concepts>
#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>

namespace mrg::scene
{
    // Scene lifetime is a route-registration policy, not a decision made by
    // the Scene object itself.
    enum class SceneRetention : std::uint8_t
    {
        // Construct on first entry, then retain and reuse the same object.
        KeepAlive,

        // Construct on every entry, then shut down and destroy on exit.
        DestroyOnExit,
    };

    // Owns all registered Scene factories and the objects created from them.
    // Every transition is applied after Update returns, so an active Scene is
    // never ended or destroyed from inside one of its own member functions.
    class SceneManager final
    {
    public:
        using SceneFactory =
            std::function<std::unique_ptr<GameScene>()>;

        SceneManager() = default;
        ~SceneManager();

        SceneManager(const SceneManager&) = delete;
        SceneManager& operator=(const SceneManager&) = delete;

        void Initialize(const EngineServices& services);

        // Registers one route and its lifetime policy. Registration does not
        // create the Scene; creation is deferred until the route is entered.
        [[nodiscard]] bool RegisterScene(
            std::string sceneId,
            SceneRetention retention,
            SceneFactory factory);

        // Constructor arguments are copied into the factory because a
        // DestroyOnExit Scene may need to be constructed more than once.
        template <typename SceneType, typename... Arguments>
            requires std::derived_from<SceneType, GameScene> &&
                (std::copy_constructible<
                    std::decay_t<Arguments>> && ...)
        [[nodiscard]] bool RegisterScene(
            std::string sceneId,
            const SceneRetention retention,
            Arguments&&... arguments)
        {
            auto constructorArguments =
                std::tuple<std::decay_t<Arguments>...>(
                    std::forward<Arguments>(arguments)...);

            SceneFactory factory =
                [constructorArguments =
                     std::move(constructorArguments)]()
                    -> std::unique_ptr<GameScene>
                {
                    return std::apply(
                        [](const auto&... values)
                            -> std::unique_ptr<GameScene>
                        {
                            return std::make_unique<SceneType>(values...);
                        },
                        constructorArguments);
                };

            return RegisterScene(
                std::move(sceneId),
                retention,
                std::move(factory));
        }

        // Start is immediate and is intended only for Client initialization.
        // It creates the initial Scene if needed, then calls BeginScene and
        // the initial OnResize.
        [[nodiscard]] bool Start(std::string_view sceneId);

        // All Scene changes use the same ID-based, deferred route operation.
        [[nodiscard]] bool ChangeScene(std::string_view sceneId);

        void Quit() noexcept;

        [[nodiscard]] bool Update(const UpdateContext& context);
        void Render(const graphics::RenderContext& context);
        void OnResize(std::uint32_t width, std::uint32_t height);
        void Shutdown() noexcept;

        // ContainsScene reports whether an ID is registered, even if its
        // lazily created object does not exist yet.
        [[nodiscard]] bool ContainsScene(std::string_view sceneId) const;
        [[nodiscard]] std::string_view CurrentSceneId() const noexcept;
        [[nodiscard]] GameScene* CurrentScene() const noexcept;
        [[nodiscard]] bool IsCurrentSceneTransient() const noexcept;

    private:
        struct RegisteredScene final
        {
            SceneRetention retention{SceneRetention::KeepAlive};
            SceneFactory factory;
            std::unique_ptr<GameScene> retainedScene;
        };

        enum class PendingAction
        {
            None,
            Change,
            Quit,
        };

        [[nodiscard]] RegisteredScene* FindRegistration(
            std::string_view sceneId);
        [[nodiscard]] const RegisteredScene* FindRegistration(
            std::string_view sceneId) const;
        [[nodiscard]] std::unique_ptr<GameScene> CreateScene(
            const RegisteredScene& registration) const;
        [[nodiscard]] GameScene* PrepareScene(
            RegisteredScene& registration,
            std::unique_ptr<GameScene>& transientScene);
        [[nodiscard]] bool ApplyPendingAction();
        void ActivateScene(GameScene& scene, std::string sceneId);
        void EndCurrentScene();
        void DestroyActiveTransientScene() noexcept;

        const EngineServices* services_{};
        std::unordered_map<std::string, RegisteredScene> registrations_;
        std::unique_ptr<GameScene> transientScene_;
        GameScene* currentScene_{};
        std::string currentSceneId_;
        std::string pendingSceneId_;
        std::uint32_t width_{};
        std::uint32_t height_{};
        PendingAction pendingAction_{PendingAction::None};
        bool initialized_{};
        bool started_{};
    };
}
// ===== END Engine\Core\Scene\SceneManager.h =====

// ===== BEGIN Engine\Core\Client\SceneGameClient.h =====


#include <string_view>

namespace mrg::scene
{
    // Client contract adapter for games organized as switchable scenes.
    // Initialize creates the manager, calls RegisterScenes, then activates
    // InitialSceneId.  All later callbacks are forwarded to SceneManager.
    class SceneGameClient : public IGameClient
    {
    public:
        ~SceneGameClient() override;

        void Initialize(const EngineServices& services) final;
        [[nodiscard]] bool Update(const UpdateContext& context) final;
        void Render(const graphics::RenderContext& context) final;
        void OnResize(std::uint32_t width, std::uint32_t height) final;
        void Shutdown() noexcept final;

    protected:
        virtual void RegisterScenes(SceneManager& scenes) = 0;
        [[nodiscard]] virtual std::string_view InitialSceneId() const noexcept = 0;

        [[nodiscard]] SceneManager& Scenes() noexcept;
        [[nodiscard]] const SceneManager& Scenes() const noexcept;

    private:
        SceneManager scenes_;
        bool initialized_{};
    };
}
// ===== END Engine\Core\Client\SceneGameClient.h =====

